import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Image from "next/image";
import MenuItems from "./components/menuItems";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="w-full h-auto bg-[#f4f4f4] sticky top-0 left-0 z-10">
          <nav className="flex items-center justify-between px-2">
            <div className="logo">
              <Image src='/defaultLogo.png' alt="logo" priority ={true} height={500} width={170}  className="w-auto h-auto"/>
            </div>
            <MenuItems/>
          </nav>
        </header>
        <main className="container mx-auto min-h-screen">
          <div className="px-4">
            {children}
          </div>
        </main>
        <footer className="w-full h-[75px] bg-[#f4f4f4] relative bottom-0">

        </footer>
      </body>
    </html>
  );
}

